name: Compile LaTeX

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build_paper:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          compiler: latexmk
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: The_Enchan_Field_Paper
          path: main.pdf